import 'package:flutter/material.dart';
import 'package:cv_ganerator/features/templates/models/resume_template.dart';

class TemplateCatalog {
  static const _defaultOrder = [
    'summary',
    'experience',
    'education',
    'skills',
    'projects',
    'certifications',
    'languages',
    'awards',
    'volunteer',
    'publications',
    'references',
    'interests',
  ];

  static const _academicOrder = [
    'summary',
    'education',
    'publications',
    'experience',
    'projects',
    'awards',
    'certifications',
    'skills',
    'languages',
    'volunteer',
    'references',
    'interests',
  ];

  static const _techOrder = [
    'summary',
    'skills',
    'experience',
    'projects',
    'education',
    'certifications',
    'languages',
    'awards',
    'volunteer',
    'publications',
    'references',
    'interests',
  ];

  static List<ResumeTemplate> get all => [
        _ats(
          id: 'ats_classic',
          name: 'ATS Classic',
          description: 'A traditional single-column resume with numbered sections and clear labels.',
          tags: ['ats', 'classic', 'professional', 'business'],
          bestFor: ['Corporate jobs', 'Recruiters', 'Office roles'],
          layout: TemplateLayoutType.atsSingle,
          titleStyle: SectionTitleStyle.numbered,
          experience: ExperienceStyle.datedLeft,
          featured: true,
          popular: true,
        ),
        _ats(
          id: 'ats_professional',
          name: 'ATS Professional',
          description: 'Clean recruiter-friendly layout with strong headings and generous scanning space.',
          tags: ['ats', 'professional', 'recruiter'],
          bestFor: ['Business', 'Management', 'HR'],
          layout: TemplateLayoutType.atsClean,
          titleStyle: SectionTitleStyle.underline,
          skill: SkillStyle.commaList,
          primary: const Color(0xFF1E3A5F),
        ),
        _ats(
          id: 'ats_clean',
          name: 'ATS Clean',
          description: 'Minimal rules, standard headings, and a logical reading order for parsers.',
          tags: ['ats', 'clean', 'minimal', 'simple'],
          bestFor: ['Entry level', 'Administration', 'Support'],
          layout: TemplateLayoutType.atsClean,
          titleStyle: SectionTitleStyle.minimal,
          divider: DividerStyle.none,
          skill: SkillStyle.list,
          spacing: const TemplateSpacing(pageMargin: 32, sectionSpacing: 14),
        ),
        _ats(
          id: 'ats_executive',
          name: 'ATS Executive',
          description: 'A composed executive CV with centered identity and conservative typography.',
          tags: ['ats', 'executive', 'leadership'],
          bestFor: ['Directors', 'Leadership', 'Consulting'],
          layout: TemplateLayoutType.executiveCenter,
          header: HeaderStyle.center,
          titleStyle: SectionTitleStyle.uppercase,
          experience: ExperienceStyle.classic,
          primary: const Color(0xFF111827),
          typography: const TemplateTypography(nameSize: 24, headingFont: 'Lato', bodyFont: 'Lato'),
        ),
        _ats(
          id: 'ats_corporate',
          name: 'ATS Corporate',
          description: 'Two-column contact header and a structured body built for corporate ATS systems.',
          tags: ['ats', 'corporate', 'business'],
          bestFor: ['Finance', 'Operations', 'Corporate'],
          layout: TemplateLayoutType.twoColumn,
          header: HeaderStyle.stacked,
          skill: SkillStyle.columns,
          primary: const Color(0xFF1D4E89),
        ),
        _ats(
          id: 'ats_minimal',
          name: 'ATS Minimal',
          description: 'Ultra-simple one-column layout with no graphics and high-contrast text.',
          tags: ['ats', 'minimal', 'simple'],
          bestFor: ['Government', 'Legal', 'Academic applications'],
          layout: TemplateLayoutType.atsClean,
          divider: DividerStyle.thin,
          skill: SkillStyle.commaList,
          titleStyle: SectionTitleStyle.uppercase,
          typography: const TemplateTypography(nameSize: 22, bodySize: 10.5, headingFont: 'Noto Sans', bodyFont: 'Noto Sans'),
        ),
        _ats(
          id: 'ats_modern',
          name: 'ATS Modern',
          description: 'Modern spacing with still-parseable headings and a left accent rule.',
          tags: ['ats', 'modern', 'professional'],
          bestFor: ['Marketing', 'Product', 'Operations'],
          layout: TemplateLayoutType.atsSingle,
          titleStyle: SectionTitleStyle.sidebarBar,
          skill: SkillStyle.chips,
          primary: const Color(0xFF2563EB),
        ),
        _ats(
          id: 'ats_simple',
          name: 'ATS Simple',
          description: 'Straightforward contact line, compact experience blocks, and no sidebar.',
          tags: ['ats', 'simple', 'one page'],
          bestFor: ['Students', 'Career changers', 'Internships'],
          layout: TemplateLayoutType.compact,
          experience: ExperienceStyle.compact,
          education: EducationStyle.compact,
          skill: SkillStyle.list,
        ),
        _ats(
          id: 'ats_business',
          name: 'ATS Business',
          description: 'Business-first hierarchy with company-forward experience lines.',
          tags: ['ats', 'business', 'corporate'],
          bestFor: ['Sales', 'Account management', 'Business analysis'],
          layout: TemplateLayoutType.atsSingle,
          header: HeaderStyle.left,
          experience: ExperienceStyle.classic,
          titleStyle: SectionTitleStyle.underline,
          primary: const Color(0xFF0F4C5C),
        ),
        _ats(
          id: 'ats_recruiter',
          name: 'ATS Recruiter',
          description: 'Optimized for recruiter scanning: skills near the top, short bullets, clear dates.',
          tags: ['ats', 'recruiter', 'hiring'],
          bestFor: ['Job boards', 'Recruiters', 'High-volume hiring'],
          layout: TemplateLayoutType.atsClean,
          skill: SkillStyle.columns,
          experience: ExperienceStyle.datedLeft,
          defaultOrder: const ['summary', 'skills', 'experience', 'education', 'certifications', 'languages', 'projects', 'awards', 'volunteer', 'publications', 'references', 'interests'],
          popular: true,
        ),
        _modern(
          id: 'modern_blue',
          name: 'Modern Blue',
          description: 'Fresh blue header band with a balanced two-column body.',
          tags: ['modern', 'blue', 'professional'],
          bestFor: ['Business', 'Marketing', 'Office jobs'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.banner,
          photo: PhotoStyle.circle,
          skill: SkillStyle.chips,
          primary: const Color(0xFF1F5AA6),
          featured: true,
          popular: true,
        ),
        _modern(
          id: 'modern_teal',
          name: 'Modern Teal',
          description: 'Teal left sidebar, circular photo, and chip-based skills.',
          tags: ['modern', 'teal', 'sidebar'],
          bestFor: ['Healthcare', 'Education', 'NGOs'],
          layout: TemplateLayoutType.modernSidebar,
          header: HeaderStyle.sidebar,
          photo: PhotoStyle.circle,
          skill: SkillStyle.bars,
          primary: const Color(0xFF0D9488),
          sidebar: const Color(0xFF134E4A),
        ),
        _modern(
          id: 'modern_indigo',
          name: 'Modern Indigo',
          description: 'Indigo split header with photo on the right and timeline experience.',
          tags: ['modern', 'indigo', 'timeline'],
          bestFor: ['Product', 'UX', 'Strategy'],
          layout: TemplateLayoutType.modernSplit,
          header: HeaderStyle.split,
          photo: PhotoStyle.square,
          experience: ExperienceStyle.timeline,
          skill: SkillStyle.boxed,
          primary: const Color(0xFF3730A3),
        ),
        _modern(
          id: 'modern_gray',
          name: 'Modern Gray',
          description: 'Quiet gray palette, thin rules, and a compact two-column grid.',
          tags: ['modern', 'gray', 'minimal', 'professional'],
          bestFor: ['Consulting', 'Operations', 'Finance'],
          layout: TemplateLayoutType.twoColumn,
          photo: PhotoStyle.none,
          skill: SkillStyle.list,
          primary: const Color(0xFF4B5563),
          divider: DividerStyle.thin,
        ),
        _modern(
          id: 'modern_black',
          name: 'Modern Black',
          description: 'High-contrast black header with white type and a structured body.',
          tags: ['modern', 'black', 'bold'],
          bestFor: ['Creative direction', 'Branding', 'Media'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.banner,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.chips,
          primary: const Color(0xFF111827),
          typography: const TemplateTypography(headingFont: 'Montserrat', bodyFont: 'Inter', nameSize: 28, letterSpacing: 0.8),
        ),
        _modern(
          id: 'modern_split',
          name: 'Modern Split',
          description: 'Name and contact split across a two-tone header with a clean body.',
          tags: ['modern', 'split', 'layout'],
          bestFor: ['Design', 'Marketing', 'Communications'],
          layout: TemplateLayoutType.modernSplit,
          header: HeaderStyle.split,
          photo: PhotoStyle.circle,
          skill: SkillStyle.columns,
          primary: const Color(0xFF2563EB),
        ),
        _modern(
          id: 'modern_sidebar',
          name: 'Modern Sidebar',
          description: 'Dark information sidebar for contact, skills, and languages.',
          tags: ['modern', 'sidebar', 'two column'],
          bestFor: ['Managers', 'Analysts', 'Coordinators'],
          layout: TemplateLayoutType.modernSidebar,
          header: HeaderStyle.sidebar,
          photo: PhotoStyle.circle,
          skill: SkillStyle.bars,
          primary: const Color(0xFF1D4ED8),
          featured: true,
        ),
        _modern(
          id: 'modern_timeline',
          name: 'Modern Timeline',
          description: 'Vertical timeline for experience with a slim accent rail.',
          tags: ['modern', 'timeline', 'experience'],
          bestFor: ['Career growth stories', 'Project roles', 'Consulting'],
          layout: TemplateLayoutType.modernTimeline,
          experience: ExperienceStyle.timeline,
          skill: SkillStyle.chips,
          photo: PhotoStyle.none,
          primary: const Color(0xFF0EA5E9),
        ),
        _modern(
          id: 'modern_professional',
          name: 'Modern Professional',
          description: 'Polished all-rounder with a left header stack and chip skills.',
          tags: ['modern', 'ats', 'professional', 'business'],
          bestFor: ['Business', 'Management', 'Marketing', 'Office jobs'],
          layout: TemplateLayoutType.twoColumn,
          header: HeaderStyle.left,
          photo: PhotoStyle.square,
          skill: SkillStyle.chips,
          ats: true,
          featured: true,
          popular: true,
        ),
        _modern(
          id: 'modern_clean',
          name: 'Modern Clean',
          description: 'Airy layout, small caps headings, and restrained color.',
          tags: ['modern', 'clean', 'minimal'],
          bestFor: ['Startups', 'Product teams', 'Remote roles'],
          layout: TemplateLayoutType.atsClean,
          photo: PhotoStyle.circle,
          skill: SkillStyle.list,
          titleStyle: SectionTitleStyle.minimal,
          primary: const Color(0xFF334155),
          spacing: const TemplateSpacing(pageMargin: 34, sectionSpacing: 18),
        ),
        _exec(
          id: 'executive_classic',
          name: 'Executive Classic',
          description: 'Centered name, hairline rules, and a conservative serif heading.',
          tags: ['executive', 'classic', 'leadership'],
          bestFor: ['C-level', 'Directors', 'Board roles'],
          layout: TemplateLayoutType.executiveCenter,
          header: HeaderStyle.center,
          photo: PhotoStyle.none,
          skill: SkillStyle.commaList,
          primary: const Color(0xFF1F2937),
          typography: const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Source Sans', nameSize: 28),
        ),
        _exec(
          id: 'executive_elite',
          name: 'Executive Elite',
          description: 'Wide letter-spacing, navy rules, and a composed two-column summary.',
          tags: ['executive', 'elite', 'navy'],
          bestFor: ['Finance leadership', 'Strategy', 'Consulting partners'],
          layout: TemplateLayoutType.twoColumn,
          header: HeaderStyle.center,
          skill: SkillStyle.columns,
          primary: const Color(0xFF0A2540),
          typography: const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Lato', letterSpacing: 1.2, nameSize: 26),
        ),
        _exec(
          id: 'executive_black',
          name: 'Executive Black',
          description: 'Monochrome executive presentation with strong name hierarchy.',
          tags: ['executive', 'black', 'minimal'],
          bestFor: ['Legal', 'Private equity', 'Senior operations'],
          layout: TemplateLayoutType.executiveCenter,
          photo: PhotoStyle.none,
          divider: DividerStyle.thick,
          primary: const Color(0xFF111827),
        ),
        _exec(
          id: 'executive_minimal',
          name: 'Executive Minimal',
          description: 'Quiet luxury: lots of whitespace and thin gold-adjacent rules.',
          tags: ['executive', 'minimal', 'elegant'],
          bestFor: ['Architecture', 'Luxury brands', 'Advisory'],
          layout: TemplateLayoutType.elegantSerif,
          header: HeaderStyle.center,
          divider: DividerStyle.thin,
          skill: SkillStyle.list,
          primary: const Color(0xFF44403C),
          spacing: const TemplateSpacing(pageMargin: 36, sectionSpacing: 20),
        ),
        _exec(
          id: 'executive_gold',
          name: 'Executive Gold',
          description: 'Navy body with a refined gold accent reserved for titles and rules.',
          tags: ['executive', 'gold', 'premium'],
          bestFor: ['Hospitality leadership', 'Wealth', 'Executive search'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.banner,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.commaList,
          primary: const Color(0xFFB45309),
          colors: const TemplateColors(
            primary: Color(0xFFB45309),
            secondary: Color(0xFF1F2937),
            sidebar: Color(0xFF111827),
          ),
        ),
        _creative(
          id: 'creative_portfolio',
          name: 'Creative Portfolio',
          description: 'Asymmetric header and project-forward structure for designers.',
          tags: ['creative', 'portfolio', 'design'],
          bestFor: ['Designers', 'Art directors', 'Illustrators'],
          layout: TemplateLayoutType.creativeAsymmetric,
          header: HeaderStyle.split,
          photo: PhotoStyle.square,
          skill: SkillStyle.boxed,
          experience: ExperienceStyle.boxed,
          primary: const Color(0xFF7C3AED),
          featured: true,
        ),
        _creative(
          id: 'creative_designer',
          name: 'Creative Designer',
          description: 'Bold name, stacked header, and visual skill boxes.',
          tags: ['creative', 'designer', 'bold'],
          bestFor: ['UI designers', 'Brand designers', 'Studios'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.stacked,
          photo: PhotoStyle.circle,
          skill: SkillStyle.bars,
          primary: const Color(0xFFDB2777),
          typography: const TemplateTypography(headingFont: 'Poppins', bodyFont: 'Poppins', nameSize: 30),
        ),
        _creative(
          id: 'creative_bold',
          name: 'Creative Bold',
          description: 'Large typographic name and a thick accent column.',
          tags: ['creative', 'bold', 'color'],
          bestFor: ['Campaign roles', 'Content', 'Creative strategy'],
          layout: TemplateLayoutType.rightSidebar,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.chips,
          primary: const Color(0xFFDC2626),
          sidebar: const Color(0xFF7F1D1D),
        ),
        _creative(
          id: 'creative_sidebar',
          name: 'Creative Sidebar',
          description: 'Color-blocked sidebar with a light content column.',
          tags: ['creative', 'sidebar', 'color block'],
          bestFor: ['Agencies', 'Freelance', 'Studio roles'],
          layout: TemplateLayoutType.modernSidebar,
          header: HeaderStyle.sidebar,
          photo: PhotoStyle.circle,
          skill: SkillStyle.bars,
          primary: const Color(0xFFEA580C),
          sidebar: const Color(0xFF9A3412),
        ),
        _creative(
          id: 'creative_gradient',
          name: 'Creative Gradient',
          description: 'Soft header wash with otherwise professional body content.',
          tags: ['creative', 'gradient', 'modern'],
          bestFor: ['Digital design', 'Social', 'Brand'],
          layout: TemplateLayoutType.creativeGradient,
          header: HeaderStyle.banner,
          photo: PhotoStyle.circle,
          skill: SkillStyle.chips,
          primary: const Color(0xFF4F46E5),
        ),
        _creative(
          id: 'creative_timeline',
          name: 'Creative Timeline',
          description: 'Story-like career timeline with accent markers.',
          tags: ['creative', 'timeline', 'story'],
          bestFor: ['Career pivots', 'Freelance history', 'Studios'],
          layout: TemplateLayoutType.modernTimeline,
          experience: ExperienceStyle.timeline,
          photo: PhotoStyle.square,
          skill: SkillStyle.boxed,
          primary: const Color(0xFF0D9488),
        ),
        _creative(
          id: 'creative_minimal',
          name: 'Creative Minimal',
          description: 'Quiet creative layout with a single accent bar and lots of air.',
          tags: ['creative', 'minimal', 'editorial'],
          bestFor: ['Editorial', 'Photography', 'Architecture'],
          layout: TemplateLayoutType.creativeAsymmetric,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.list,
          divider: DividerStyle.none,
          primary: const Color(0xFF44403C),
          spacing: const TemplateSpacing(pageMargin: 36, sectionSpacing: 22),
        ),
        _tech(
          id: 'developer',
          name: 'Developer',
          description: 'Skills-first developer CV with project and stack emphasis.',
          tags: ['developer', 'tech', 'software', 'ats'],
          bestFor: ['Software engineers', 'Full-stack', 'Mobile'],
          layout: TemplateLayoutType.techGrid,
          skill: SkillStyle.boxed,
          photo: PhotoStyle.none,
          ats: true,
          featured: true,
          popular: true,
          primary: const Color(0xFF0F766E),
        ),
        _tech(
          id: 'software_engineer',
          name: 'Software Engineer',
          description: 'Two-column engineering resume with dated experience and skill groups.',
          tags: ['software', 'engineer', 'tech', 'ats'],
          bestFor: ['Backend', 'Frontend', 'Platform'],
          layout: TemplateLayoutType.twoColumn,
          skill: SkillStyle.columns,
          experience: ExperienceStyle.datedLeft,
          ats: true,
          primary: const Color(0xFF1D4ED8),
        ),
        _tech(
          id: 'tech_professional',
          name: 'Tech Professional',
          description: 'Balanced tech CV for specialists who work across product and engineering.',
          tags: ['tech', 'professional', 'ats'],
          bestFor: ['IT', 'Solutions', 'Implementation'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.banner,
          skill: SkillStyle.chips,
          photo: PhotoStyle.circle,
          ats: true,
          primary: const Color(0xFF0369A1),
        ),
        _tech(
          id: 'tech_sidebar',
          name: 'Tech Sidebar',
          description: 'Sidebar for stack, languages, and links with a dense experience column.',
          tags: ['tech', 'sidebar', 'developer'],
          bestFor: ['DevOps', 'Data engineering', 'Security'],
          layout: TemplateLayoutType.modernSidebar,
          header: HeaderStyle.sidebar,
          skill: SkillStyle.bars,
          photo: PhotoStyle.square,
          primary: const Color(0xFF4338CA),
          sidebar: const Color(0xFF1E1B4B),
        ),
        _tech(
          id: 'tech_minimal',
          name: 'Tech Minimal',
          description: 'Sparse, parser-friendly engineering layout with monospace-inspired headings.',
          tags: ['tech', 'minimal', 'ats'],
          bestFor: ['Open source', 'Startups', 'Contracting'],
          layout: TemplateLayoutType.atsClean,
          skill: SkillStyle.commaList,
          photo: PhotoStyle.none,
          ats: true,
          titleStyle: SectionTitleStyle.minimal,
          primary: const Color(0xFF111827),
          typography: const TemplateTypography(headingFont: 'Source Sans', bodyFont: 'Source Sans', nameSize: 24),
        ),
        _tech(
          id: 'data_scientist',
          name: 'Data Scientist',
          description: 'Projects and publications sit higher for research-minded data roles.',
          tags: ['data', 'science', 'tech', 'research'],
          bestFor: ['Data science', 'ML', 'Analytics'],
          layout: TemplateLayoutType.twoColumn,
          skill: SkillStyle.bars,
          photo: PhotoStyle.none,
          primary: const Color(0xFF0F766E),
          defaultOrder: const ['summary', 'skills', 'projects', 'experience', 'education', 'publications', 'certifications', 'languages', 'awards', 'volunteer', 'references', 'interests'],
        ),
        _tech(
          id: 'product_manager',
          name: 'Product Manager',
          description: 'Outcome-focused layout with summary, impact bullets, and compact skills.',
          tags: ['product', 'manager', 'tech', 'business'],
          bestFor: ['Product management', 'Program', 'Strategy'],
          layout: TemplateLayoutType.modernSplit,
          header: HeaderStyle.split,
          skill: SkillStyle.chips,
          photo: PhotoStyle.circle,
          experience: ExperienceStyle.classic,
          primary: const Color(0xFF1F5AA6),
          ats: true,
        ),
        _academic(
          id: 'academic',
          name: 'Academic',
          description: 'Education and publications first, with a traditional CV reading order.',
          tags: ['academic', 'research', 'education'],
          bestFor: ['PhD candidates', 'Lecturers', 'Research staff'],
          layout: TemplateLayoutType.academic,
          skill: SkillStyle.list,
          photo: PhotoStyle.none,
          featured: true,
        ),
        _academic(
          id: 'researcher',
          name: 'Researcher',
          description: 'Dense research CV with publications and awards in the primary column.',
          tags: ['academic', 'researcher', 'publications'],
          bestFor: ['Postdocs', 'Lab researchers', 'Think tanks'],
          layout: TemplateLayoutType.twoColumn,
          skill: SkillStyle.columns,
          photo: PhotoStyle.none,
          primary: const Color(0xFF1E3A5F),
        ),
        _academic(
          id: 'professor',
          name: 'Professor',
          description: 'Formal serif CV suited to faculty appointments and tenure packets.',
          tags: ['academic', 'professor', 'faculty'],
          bestFor: ['Faculty', 'Teaching', 'University administration'],
          layout: TemplateLayoutType.elegantSerif,
          header: HeaderStyle.center,
          skill: SkillStyle.commaList,
          typography: const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Merriweather', nameSize: 24, bodySize: 10.5),
        ),
        _academic(
          id: 'academic_classic',
          name: 'Academic Classic',
          description: 'Classic academic headings, no photo, and a strict single column.',
          tags: ['academic', 'classic', 'cv'],
          bestFor: ['Humanities', 'Social sciences', 'Fellowships'],
          layout: TemplateLayoutType.atsSingle,
          titleStyle: SectionTitleStyle.underline,
          photo: PhotoStyle.none,
          skill: SkillStyle.list,
        ),
        _academic(
          id: 'research_cv',
          name: 'Research CV',
          description: 'Research-first international CV with room for grants and publications.',
          tags: ['academic', 'research', 'international'],
          bestFor: ['Grants', 'International fellowships', 'Labs'],
          layout: TemplateLayoutType.academic,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.list,
          primary: const Color(0xFF155E75),
        ),
        _elegant(
          id: 'elegant',
          name: 'Elegant',
          description: 'Serif headings, generous margins, and hairline dividers.',
          tags: ['elegant', 'premium', 'serif'],
          bestFor: ['Consulting', 'Luxury', 'Client-facing roles'],
          layout: TemplateLayoutType.elegantSerif,
          header: HeaderStyle.center,
          photo: PhotoStyle.circle,
          skill: SkillStyle.commaList,
          featured: true,
        ),
        _elegant(
          id: 'elegant_minimal',
          name: 'Elegant Minimal',
          description: 'Almost no decoration — just type, space, and a single accent rule.',
          tags: ['elegant', 'minimal', 'serif'],
          bestFor: ['Architecture', 'Editorial', 'Design leadership'],
          layout: TemplateLayoutType.elegantSerif,
          photo: PhotoStyle.none,
          divider: DividerStyle.thin,
          skill: SkillStyle.list,
          titleStyle: SectionTitleStyle.minimal,
          spacing: const TemplateSpacing(pageMargin: 38, sectionSpacing: 22),
        ),
        _elegant(
          id: 'elegant_serif',
          name: 'Elegant Serif',
          description: 'Fully serif document with classical centered masthead.',
          tags: ['elegant', 'serif', 'classic'],
          bestFor: ['Publishing', 'Law-adjacent', 'Culture'],
          layout: TemplateLayoutType.executiveCenter,
          header: HeaderStyle.center,
          photo: PhotoStyle.none,
          skill: SkillStyle.commaList,
          typography: const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Merriweather', nameSize: 26),
        ),
        _elegant(
          id: 'premium_classic',
          name: 'Premium Classic',
          description: 'Premium classic with a navy nameplate and structured sections.',
          tags: ['premium', 'classic', 'professional'],
          bestFor: ['Banking', 'Consulting', 'Client service'],
          layout: TemplateLayoutType.headerBand,
          header: HeaderStyle.banner,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.columns,
          primary: const Color(0xFF0A2540),
        ),
        _elegant(
          id: 'premium_modern',
          name: 'Premium Modern',
          description: 'Modern premium mix: sidebar contact and serif headings.',
          tags: ['premium', 'modern', 'elegant'],
          bestFor: ['Product leadership', 'Brand', 'Strategy'],
          layout: TemplateLayoutType.modernSidebar,
          header: HeaderStyle.sidebar,
          photo: PhotoStyle.circle,
          skill: SkillStyle.chips,
          primary: const Color(0xFF1F5AA6),
          typography: const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Inter'),
        ),
        _elegant(
          id: 'black_white_elite',
          name: 'Black & White Elite',
          description: 'Print-perfect monochrome elite layout with strong contrast.',
          tags: ['elegant', 'black', 'white', 'elite', 'ats'],
          bestFor: ['Formal applications', 'Print', 'Executive search'],
          layout: TemplateLayoutType.executiveCenter,
          photo: PhotoStyle.none,
          skill: SkillStyle.list,
          divider: DividerStyle.doubleLine,
          ats: true,
          primary: const Color(0xFF111827),
        ),
        _add(
          id: 'two_column_pro',
          name: 'Two Column Pro',
          description: 'Professional 35/65 grid with contact and skills in the left rail.',
          tags: ['two column', 'professional', 'modern'],
          bestFor: ['Managers', 'Analysts', 'General professional'],
          layout: TemplateLayoutType.twoColumn,
          photo: PhotoStyle.square,
          skill: SkillStyle.bars,
          primary: const Color(0xFF1F5AA6),
          popular: true,
        ),
        _add(
          id: 'compact_professional',
          name: 'Compact Professional',
          description: 'Dense one-page layout that keeps more content above the fold.',
          tags: ['compact', 'one page', 'professional', 'ats'],
          bestFor: ['Experienced hires', 'One-page policies', 'Recruiters'],
          layout: TemplateLayoutType.compact,
          skill: SkillStyle.chips,
          experience: ExperienceStyle.compact,
          education: EducationStyle.compact,
          ats: true,
          spacing: const TemplateSpacing(pageMargin: 22, sectionSpacing: 10, itemSpacing: 6),
          typography: const TemplateTypography(nameSize: 22, headingSize: 11, bodySize: 9.5, lineHeight: 1.28),
        ),
        _add(
          id: 'timeline_pro',
          name: 'Timeline Pro',
          description: 'Career timeline with dates on a vertical rail and compact side details.',
          tags: ['timeline', 'professional', 'modern'],
          bestFor: ['Consultants', 'Contractors', 'Career narratives'],
          layout: TemplateLayoutType.modernTimeline,
          experience: ExperienceStyle.timeline,
          skill: SkillStyle.columns,
          photo: PhotoStyle.circle,
          primary: const Color(0xFF0F766E),
        ),
        _add(
          id: 'simple_one_page',
          name: 'Simple One Page',
          description: 'Simple, friendly one-page resume with standard headings.',
          tags: ['simple', 'one page', 'ats', 'minimal'],
          bestFor: ['Students', 'First jobs', 'Career changers'],
          layout: TemplateLayoutType.atsClean,
          skill: SkillStyle.commaList,
          photo: PhotoStyle.none,
          ats: true,
          titleStyle: SectionTitleStyle.underline,
        ),
        _add(
          id: 'professional_international',
          name: 'Professional International',
          description: 'Photo-friendly international CV with personal details in a header grid.',
          tags: ['international', 'photo', 'europe', 'uae', 'pakistan', 'india'],
          bestFor: ['Europe', 'UAE', 'Pakistan', 'India', 'International companies'],
          layout: TemplateLayoutType.international,
          header: HeaderStyle.split,
          photo: PhotoStyle.rectangle,
          skill: SkillStyle.bars,
          primary: const Color(0xFF1D4E89),
          featured: true,
        ),
      ];

  static ResumeTemplate _ats({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.left,
    PhotoStyle photo = PhotoStyle.none,
    SkillStyle skill = SkillStyle.list,
    ExperienceStyle experience = ExperienceStyle.classic,
    EducationStyle education = EducationStyle.classic,
    DividerStyle divider = DividerStyle.thin,
    SectionTitleStyle titleStyle = SectionTitleStyle.uppercase,
    Color primary = const Color(0xFF1F2937),
    TemplateTypography typography = const TemplateTypography(
      headingFont: 'Source Sans',
      bodyFont: 'Source Sans',
      nameSize: 24,
    ),
    TemplateSpacing spacing = const TemplateSpacing(),
    List<String>? defaultOrder,
    bool featured = false,
    bool popular = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.ats,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      experienceStyle: experience,
      educationStyle: education,
      dividerStyle: divider,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(primary: primary),
      typography: typography,
      spacing: spacing,
      atsFriendly: true,
      featured: featured,
      popular: popular,
      pageCount: pageCount,
      defaultSectionOrder: defaultOrder ?? _defaultOrder,
      accentTargets: const {'headers', 'lines'},
    );
  }

  static ResumeTemplate _modern({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.left,
    PhotoStyle photo = PhotoStyle.none,
    SkillStyle skill = SkillStyle.chips,
    ExperienceStyle experience = ExperienceStyle.classic,
    DividerStyle divider = DividerStyle.accent,
    SectionTitleStyle titleStyle = SectionTitleStyle.uppercase,
    Color primary = const Color(0xFF1F5AA6),
    Color? sidebar,
    TemplateTypography typography = const TemplateTypography(headingFont: 'Inter', bodyFont: 'Inter'),
    TemplateSpacing spacing = const TemplateSpacing(),
    bool ats = false,
    bool featured = false,
    bool popular = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.modern,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      experienceStyle: experience,
      dividerStyle: divider,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(
        primary: primary,
        sidebar: sidebar ?? const Color(0xFF0F172A),
      ),
      typography: typography,
      spacing: spacing,
      atsFriendly: ats,
      featured: featured,
      popular: popular,
      pageCount: pageCount,
      accentTargets: const {'headers', 'lines', 'icons', 'sidebar'},
    );
  }

  static ResumeTemplate _exec({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.center,
    PhotoStyle photo = PhotoStyle.none,
    SkillStyle skill = SkillStyle.commaList,
    DividerStyle divider = DividerStyle.thin,
    Color primary = const Color(0xFF1F2937),
    TemplateTypography typography = const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Lato'),
    TemplateSpacing spacing = const TemplateSpacing(pageMargin: 32, sectionSpacing: 18),
    TemplateColors? colors,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.executive,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      dividerStyle: divider,
      sectionTitleStyle: SectionTitleStyle.uppercase,
      colors: colors ?? TemplateColors(primary: primary),
      typography: typography,
      spacing: spacing,
      atsFriendly: true,
      pageCount: pageCount,
      accentTargets: const {'headers', 'lines'},
    );
  }

  static ResumeTemplate _creative({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.left,
    PhotoStyle photo = PhotoStyle.circle,
    SkillStyle skill = SkillStyle.chips,
    ExperienceStyle experience = ExperienceStyle.classic,
    DividerStyle divider = DividerStyle.accent,
    Color primary = const Color(0xFF7C3AED),
    Color? sidebar,
    TemplateTypography typography = const TemplateTypography(headingFont: 'Poppins', bodyFont: 'Inter'),
    TemplateSpacing spacing = const TemplateSpacing(),
    bool featured = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.creative,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      experienceStyle: experience,
      dividerStyle: divider,
      sectionTitleStyle: SectionTitleStyle.boxed,
      colors: TemplateColors(
        primary: primary,
        sidebar: sidebar ?? primary,
      ),
      typography: typography,
      spacing: spacing,
      featured: featured,
      pageCount: pageCount,
      accentTargets: const {'headers', 'lines', 'icons', 'sidebar'},
    );
  }

  static ResumeTemplate _tech({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    SkillStyle skill = SkillStyle.boxed,
    PhotoStyle photo = PhotoStyle.none,
    HeaderStyle header = HeaderStyle.left,
    ExperienceStyle experience = ExperienceStyle.classic,
    SectionTitleStyle titleStyle = SectionTitleStyle.uppercase,
    Color primary = const Color(0xFF0F766E),
    Color? sidebar,
    TemplateTypography typography = const TemplateTypography(headingFont: 'Source Sans', bodyFont: 'Source Sans'),
    List<String>? defaultOrder,
    bool ats = false,
    bool featured = false,
    bool popular = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.tech,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      experienceStyle: experience,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(
        primary: primary,
        sidebar: sidebar ?? const Color(0xFF042F2E),
      ),
      typography: typography,
      atsFriendly: ats,
      featured: featured,
      popular: popular,
      pageCount: pageCount,
      defaultSectionOrder: defaultOrder ?? _techOrder,
      accentTargets: const {'headers', 'lines', 'icons', 'sidebar'},
    );
  }

  static ResumeTemplate _academic({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.left,
    PhotoStyle photo = PhotoStyle.none,
    SkillStyle skill = SkillStyle.list,
    SectionTitleStyle titleStyle = SectionTitleStyle.underline,
    Color primary = const Color(0xFF1F2937),
    TemplateTypography typography = const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Source Sans'),
    bool featured = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.academic,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(primary: primary),
      typography: typography,
      atsFriendly: true,
      featured: featured,
      pageCount: pageCount,
      defaultSectionOrder: _academicOrder,
      accentTargets: const {'headers', 'lines'},
    );
  }

  static ResumeTemplate _elegant({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    HeaderStyle header = HeaderStyle.center,
    PhotoStyle photo = PhotoStyle.none,
    SkillStyle skill = SkillStyle.commaList,
    DividerStyle divider = DividerStyle.thin,
    SectionTitleStyle titleStyle = SectionTitleStyle.uppercase,
    Color primary = const Color(0xFF44403C),
    TemplateTypography typography = const TemplateTypography(headingFont: 'Merriweather', bodyFont: 'Lato', nameSize: 26),
    TemplateSpacing spacing = const TemplateSpacing(pageMargin: 34, sectionSpacing: 18),
    bool ats = false,
    bool featured = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.elegant,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      dividerStyle: divider,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(primary: primary),
      typography: typography,
      spacing: spacing,
      atsFriendly: ats,
      featured: featured,
      pageCount: pageCount,
      accentTargets: const {'headers', 'lines'},
    );
  }

  static ResumeTemplate _add({
    required String id,
    required String name,
    required String description,
    required List<String> tags,
    required List<String> bestFor,
    required TemplateLayoutType layout,
    PhotoStyle photo = PhotoStyle.none,
    HeaderStyle header = HeaderStyle.left,
    SkillStyle skill = SkillStyle.list,
    ExperienceStyle experience = ExperienceStyle.classic,
    EducationStyle education = EducationStyle.classic,
    SectionTitleStyle titleStyle = SectionTitleStyle.uppercase,
    Color primary = const Color(0xFF1F5AA6),
    TemplateTypography typography = const TemplateTypography(),
    TemplateSpacing spacing = const TemplateSpacing(),
    bool ats = false,
    bool popular = false,
    bool featured = false,
    int pageCount = 1,
  }) {
    return ResumeTemplate(
      id: id,
      name: name,
      category: TemplateCategory.additional,
      description: description,
      tags: tags,
      bestFor: bestFor,
      layoutType: layout,
      headerStyle: header,
      photoStyle: photo,
      skillStyle: skill,
      experienceStyle: experience,
      educationStyle: education,
      sectionTitleStyle: titleStyle,
      colors: TemplateColors(primary: primary),
      typography: typography,
      spacing: spacing,
      atsFriendly: ats,
      popular: popular,
      featured: featured,
      pageCount: pageCount,
      accentTargets: const {'headers', 'lines', 'icons', 'sidebar'},
    );
  }
}
